### ISSUE TITLE
Missing  Npc Velastrasza

### ISSUE THREAD

**Issue by AnTOLI** [FALL1N1/Hysteria-Panda#114]
Липсва това Нпц http://www.wowhead.com/npc=45522/velastrasza в Twilight Highlands.

**Comment by Dulsse** [comment]
Когато вземеш втория куест от поредицата[ [Even Dragons Bleed] ](http://www.wowhead.com/quest=27504/even-dragons-bleed), трябва да говориш с въпросното NPC. Тя е там, но във фаза 1 - невидима за играчи.

**Comment by FALL1N1** [comment]
Трябва да имаш quest-а и дадената аура от него, иначе няма да я виждаш, ок си е.
