### ISSUE TITLE
Missing  Npc Warlord Krogg 

### ISSUE THREAD

**Issue by AnTOLI** [FALL1N1/Hysteria-Panda#115]
Липсва Нпц то да даденото място http://www.wowhead.com/npc=47493/warlord-krogg

**Comment by Dulsse** [comment]
Когато стигнеш до куеста [[The Gates of Grim Batol]](http://www.wowhead.com/quest=28097/the-gates-of-grim-batol), където трябва да говориш с въпросното NPC, за да продължиш поредицата - не се вижда. Phase 1, само като ГМ можеш да го видиш, но е там.

**Comment by Dulsse** [comment]
Когато стигнеш до куеста [[The Gates of Grim Batol]](http://www.wowhead.com/quest=28097/the-gates-of-grim-batol), където трябва да говориш с въпросното NPC, за да продължиш поредицата - не се вижда. Phase 1, само като ГМ можеш да го видиш, но е там.

**Comment by FALL1N1** [comment]
Трябва да имаш quest-а и дадената аура от него, иначе няма да я виждаш, ок си е.
