### ISSUE TITLE
Skill: Spinning crane kick

### ISSUE THREAD

**Issue by Autaila** [FALL1N1/Hysteria-Panda#22]

**Comment by FALL1N1** [comment]
[(4 \* 0.9 \* ((1.0 \* (1 + $versadmg)) \* (0.857143 \* (Mainhand Min DPS + 1 \* (Offhand Min DPS /2)) + Attack power / 3.5 - 1)) + 4 \* 0.9 \* ((1.0 \* (1 + $versadmg)) \* (0.857143 \* (Mainhand Max DPS + 1 \* (Offhand Max DPS /2)) + Attack power / 3.5 + 1))) / 2]

**Comment by FALL1N1** [comment]
test
