### ISSUE TITLE
Dungeon:Temple of the Jade Serpent

### ISSUE THREAD

**Issue by Tankistta** [FALL1N1/Hysteria-Panda#40]
Tози http://www.wowhead.com/zone=5956/temple-of-the-jade-serpent първия boss http://www.wowhead.com/npc=56448/wise-mari не работи втора фаза не прави dmg като castva магията Wash Away и тази магия също не работи http://www.wowhead.com/spell=115167/corrupted-waters#see-also-other прави 3k dmg на 0.25 sec трябва да прави 20k на 0.25 sec на Heroic mode.

**Comment by FALL1N1** [comment]
Ne e problem.
