### ISSUE TITLE
Priest-Spell:Shadow Orbs,Devouring Plague

### ISSUE THREAD

**Issue by Pavslav** [FALL1N1/Hysteria-Panda#46]
Mind Blast дава 3 стака от http://www.wowhead.com/spell=95740/shadow-orbs автоматично ,а damage-а е занижен драстично
Heal-а от http://www.wowhead.com/spell=2944/devouring-plague е много повече като няма значение  от стаковете и нанесения damage ~300k+ на тик(6-7 тика)
PS :проблема се появи на 17.01.2016(След Update-a)

**Comment by FALL1N1** [comment]
test

**Comment by Pavslav** [comment]
няма промяна http://www.wowhead.com/spell=2944/devouring-plague хеалва 100% от кръвта а трябва да е 1% зависимост от това колко орба са използвани 
http://www.wowhead.com/spell=8092/mind-blast генерира 3 орба дирекно трябва да е 1

**Comment by FALL1N1** [comment]
sled restart se testvat fixove t.e utre(27/01/2016 08:00)
