### ISSUE TITLE
Class: Frost Death Knight

### ISSUE THREAD

**Issue by Autaila** [FALL1N1/Hysteria-Panda#60]

**Comment by FALL1N1** [comment]
death decacy (todo)-    (0.132 \* ap) \* 10

**Comment by Autaila** [comment]
Дори така представено не прави толкова DnD в момента прави 1400 дмг при 20к ап

**Comment by FALL1N1** [comment]
test na vs ostanali, dnes imashe upd
prosto si komentiram formulite s (todo), nqma nujda da otgovarqte

**Comment by Autaila** [comment]
Като се върна от работа ще тествам "Frost spec". Като събера малко злато за смяна на спек и таланти ще пробвам и останалите "Blood & Unholy spec".

**Comment by Tankistta** [comment]
"Expertise" и "Armor" не работи на всички melee classove
