### ISSUE TITLE
NPC Spell: Firesworn / Eruption

### ISSUE THREAD

**Issue by Dulsse** [FALL1N1/Hysteria-Panda#80]
http://www.wowhead.com/npc=50055/firesworn - Това е NPC-то
http://www.wowhead.com/spell=93512/eruption - това е спела. Knock back ефекта е твърде силен, изхвърля играча много, много, ама МНОГО високо в небето -> играча умира от падането.

**Comment by Autaila** [comment]
По принцип така е направено да мята на 220-225 ярда.
