### ISSUE TITLE
Quest [Hostile Skies]

### ISSUE THREAD

**Issue by Min4AKK** [FALL1N1/Hysteria-Panda#90]
http://www.wowhead.com/quest=30978/hostile-skies  - не работи погледнато отвсякъде,нито може да се ползва уредът на земята до НПС-то,нито във въздуха ги има тези богомолките.

https://www.youtube.com/watch?v=QznupWv-bEM - така би трябвало да бъде

**Comment by Ritokoko** [comment]
Куеста работи просто нпс-тата са доло на земята..
