### ISSUE TITLE
MOVING BUG !!! 

### ISSUE THREAD

**Issue by Min4AKK** [FALL1N1/Hysteria-Panda#97]
Забелязал съм,че ако примерно искаш да вземеш някой куест итем,който е на земята или нещо друго(някоя професия-mining,herbalism,skining) ,а ти си на някакъв маунт и спираш и като се опитваш да вземеш итема не го отваря,ами ти казва "can't do that action while moving" или нещо от сорта,при условие,че героят е в покой.Трябва да се мръднеш леко нанякъде,за да ти се оправи.По същия начин става и със спела на монка Fist of Fury (http://www.wowhead.com/spell=113656/fists-of-fury ) . Бия някакъв моб и като имам достатъчно chi да практикувам спела върху моба,по същия начин ми казва "can't do that action while moving" ,а аз си седя на едно място и трябва да се мръдна,за да може да ми тръгне спела.

**Comment by Ritokoko** [comment]
Относно проблема с Монк не беше лошо да го пуснеш в друг репот.

**Comment by FALL1N1** [comment]
Не е проблем, има по-важни неща.
