### ISSUE TITLE
Missing  Npc Dormus the Camel-Hoarder

### ISSUE THREAD

**Issue by AnTOLI** [FALL1N1/Hysteria-Panda#98]
http://www.wowhead.com/npc=50245/dormus-the-camel-hoarder Липсва това Нпц  rare което дава моунт.

**Comment by Dulsse** [comment]
When you find the correct Mysterious Camel Figurine in Uldum, you get transported (after spending a few seconds in a Sandstorm) to the Steam Pools in Feralas, and receive the Dormus' Rage "debuff" that allows you to see this guy. If it ticks out, he "retreats" and you phase back into the normal Steam Pools.

**Comment by Dulsse** [comment]
Да се тества.

**Comment by AnTOLI** [comment]
Няма го Нпц то http://www.wowhead.com/npc=50410/mysterious-camel-figurine

**Comment by AnTOLI** [comment]
Работи .:)
